version: "3.8"

services:
  postgres-account:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_account:/var/lib/postgresql/data"

  account:
    build:
      context: ./account
      target: builder
    image: account
    env_file: account/.env
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-account
    volumes:
      - ./account:/go/src/app  # Mount your project directory into the container
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"

volumes:
  pgdata_account:
