receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "tempo:4317"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
